version: '2'
services:
  base:
    build: .
    image: devopsprocote/workshop
    restart: on-failure

  lb:
    image: dockercloud/haproxy
    links:
      - http-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
    restart: on-failure

  http-server:
    extends: base
    command: node http-server
    environment:
      - VIRTUAL_HOST=devopspro.cotejs.org
      - BALANCE=source
    ports:
      - 5000:5000

  client-service:
    extends: base
    command: node services/client-service

  contacts-service:
    extends: base
    command: node services/contacts-service
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
